version: 2
jobs:
  build:
    working_directory: /tmp/build
    docker:
      - image: alpine
    steps:
      - checkout
      - setup_remote_docker
      - deploy:
          name: Publish to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              apk --no-cache add docker bash
              docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
              docker build \
                -t codestar/circleci-scala-sbt-git-jq \
                .
              docker push codestar/circleci-scala-sbt-git-jq:release
            fi